blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('post/<slug:slug>', views.post, name="post"),
    path('category/<slug:slug>/', views.category, name="category"),
    path('search/', views.search, name="search"),
    path('create/', views.PostCreateView.as_view(), name="create"),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='blog_login'),
    path('logout/', views.custom_logout_view, name='blog_logout')
]

cart/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name= 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>', views.cart_remove, name="cart_remove")
]

website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', include('helloweb.urls')),
                  path('', include('blog.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('shop/', include('shop.urls')),
                  path('cart/', include('cart.urls')),
                  path('orders/', include('orders.urls', namespace='orders')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings


from django.utils.text import slugify


class Category(models.Model):
    slug = models.SlugField(max_length=120, unique=True)
    name = models.CharField(max_length=100, verbose_name="Назва")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Tag(models.Model):
    slug = models.SlugField(max_length=120, unique=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Post(models.Model):
    slug = models.SlugField(max_length=220, unique=True, db_index=True)
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Опис")
    published_date = models.DateTimeField(auto_created=True, verbose_name="Дата публікації")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категорія")
    auther = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор", default=1)
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True)
    image = models.URLField(
        default="https://soliloquywp.com/wp-content/uploads/2016/08/How-to-Set-a-Default-Featured-Image-in-WordPress.png")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Публікація"
        verbose_name_plural = "Публікації"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=100, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    avatar = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"Profile {self.settings.AUTH_USER_MODEL.username}"

 

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('slug', 'published_date',)


class RegisterForm(UserCreationForm):
    phone = forms.CharField(max_length=20, required=False)
    city = forms.CharField(max_length=100, required=False)
    birth_date = forms.DateTimeField(required=False)
    avatar = forms.URLField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "phone", "city", "birth_date", "avatar")

blog/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.utils.timezone import now
from django.views.generic import CreateView

from .models import Post, Category
from .forms import PostForm


def get_categories():
    all = Category.objects.all()
    half = all.count() // 2
    first_half = all[:half]
    second_half = all[half:]
    return {'cats1': first_half,
            'cats2': second_half}


def index(request):
    posts = Post.objects.all().order_by("-published_date")
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'posts': posts, 'page_obj': page_obj}
    context.update(get_categories())
    return render(request, "blog/index.html", context=context)


def about(request):
    context = {}
    return render(request, "blog/about.html", context=context)


def contact(request):
    context = {}
    return render(request, "blog/contact.html", context=context)


def post(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    context = {'post': post}
    context.update(get_categories())
    return render(request, "blog/post.html", context=context)


def category(request, slug=None):
    c = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(category=c).order_by("-published_date")
    context = {'posts': posts}
    context.update(get_categories())
    return render(request, "blog/index.html", context=context)


def search(request):
    query = request.GET.get('query')
    posts = Post.objects.filter(Q(content__icontains=query) | Q(title__icontains=query)).order_by("-published_date")
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'posts': posts, 'page_obj': page_obj}
    context.update(get_categories())
    return render(request, "blog/index.html", context=context)


# @login_required
# def create(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.published_date = now()
#             post.auther = request.user
#             post.save()
#     formCreate = PostForm()
#     context = {'formCreate': formCreate}
#     context.update(get_categories())
#     return render(request, "blog/create.html", context=context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/create.html"

    def form_valid(self, form):
        post = form.save(commit=False)
        post.published_date = now()
        post.auther = self.request.user
        post.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_categories())

        return context


def custom_logout_view(request):
    logout(request)
    return redirect('home')

templates/blog/about.html
{% extends 'blog/base.html' %}

{% block main %}

<h1 class="page-header">
    About
    <small>Secondary Text</small>
</h1>


{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'blog/css/blog-home.css'%}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    {% include 'blog/nav.html' %}

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                 {% block main %}  {% endblock %}
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                        <form method="get" action="{%url 'search' %}" class="input-group">
                            <input type="search" class="form-control" name="query">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </form>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for cat in cats1 %}
                                    <li><a href="{% url 'category' slug=cat.slug %}">{{cat.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                 {% for cat in cats2 %}
                                    <li><a href="{% url 'category' slug=cat.slug %}">{{cat.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'blog/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block main %}

<h1 class="page-header">
    Contact
    <small>Secondary Text</small>
</h1>


{% endblock %}

templates/blog/create.html
{% extends 'blog/base.html' %}

{% block main %}

<h1 class="page-header">
    Create new post
</h1>

<form action="{%url 'create'%}" method="POST">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="save" class="btn btn-default">
</form>

{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main %}

<h1 class="page-header">
    Page Heading
    <small>Secondary Text</small>
</h1>

{% for post in page_obj %}
<!-- First Blog Post -->
<div class="tags">
    {% for tag in post.tags.all %}
      <span class="tag">{{tag.name}} </span>
    {% endfor %}
</div>
<h2>
    <a href="{% url 'post' slug=post.slug %}">{{post.title}}</a>
</h2>
<p class="lead">
    by <a href="index.php">{{post.auther}}</a>
</p>
<p><span class="glyphicon glyphicon-time"></span> Posted on {{post.published_date}}</p>
<hr>
<img class="img-responsive" src="{{post.image}}" alt="">
<hr>
<p>{{post.content|truncatewords:20}}</p>
<a class="btn btn-primary" href="{% url 'post' slug=post.slug %}">Read More <span
        class="glyphicon glyphicon-chevron-right"></span></a>

{% empty %}
<p>Немає постів !</p>
{% endfor %}
<!-- Pager -->
<!--<ul class="pager">-->
<!--    <li class="previous">-->
<!--        <a href="#">&larr; Older</a>-->
<!--    </li>-->
<!--    <li class="next">-->
<!--        <a href="#">Newer &rarr;</a>-->
<!--    </li>-->
<!--</ul>-->

<nav >
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page_link" href="?page=1">First</a></li>
    <li class="page-item"><a class="page_link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
    {% endif %}

    <span>Сторінка {{ page_obj.number }} із {{page_obj.paginator.num_pages }}</span>

    {% if page_obj.has_next %}
    <li class="page-item"><a class="page_link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    <li class="page-item"><a class="page_link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
</ul>
</nav>
{% endblock %}

templates/blog/nav.html
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Logo</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <li class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'about' %}">About</a>
                </li>

                <li>
                    <a href="{% url 'contact' %}">Contact</a>
                </li>

                <li>
                    <a href="{% url 'create' %}">Create post</a>
                </li>

                <li>
                    <a href="{% url 'gallery' %}">Gallery</a>
                </li>



            <li>
                <a href="{% url 'cart:cart_detail' %}">Cart {{cart|length}}</a>
            </li>
                </ul>
            {% include 'registration/toggle_login.html' %}
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/blog/post.html
{% extends 'blog/base.html' %}

{% block main %}
                <!-- Blog Post -->
                <!-- Title -->
                <h1>{{post.title}}</h1>
                <!-- Author -->
                <p class="lead">
                    by <a href="#">{{post.auther}}</a>
                </p>
                <hr>
                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{post.published_date}}</p>
                <hr>
                <!-- Preview Image -->
                <img class="img-responsive" src="{{post.image}}" alt="">
                <hr>
                <!-- Post Content -->
                <p class="lead">{{post.content}}</p>
                <hr>
                <!-- Blog Comments -->
                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

{% endblock %}